# Generated by Django 4.2.5 on 2024-08-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_recycleuser_user_deleted_at_user_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
